### ISSUE TITLE
List on Packagist and tag an 0.1 release

### ISSUE THREAD

**Issue by mindplay-dk** [php-fig/simplecache#2]
Packages such as [scrapbook](https://github.com/matthiasmullie/scrapbook) are difficult to consume right now, because the author has been forced to include a [physical copy](https://github.com/matthiasmullie/scrapbook/tree/master/src/Psr16/psr-simplecache) of the currently unreleased interfaces.

We're building packages that depend on PSR-16 in it's current form, and the only way to do that right now, is to depend on the entire scrapbook package just to get the interfaces.

Can you please add the package to Packagist and tag an `0.1` release, so that we (and @matthiasmullie) can depend upon it, in it's current form?

I understand that PSR-16 is in-development, and that's fine - as soon as there's an `0.2` or `1.0` release, we can updated our dependencies and upgrade. Without an installable package, the situation is kind of messy.

(Even if you do not wish to tag an `0.1` release at this time, please consider listing the package on Packagist, so that at least we can depend on the current hash - at least better than copying them to each project...)

**Comment by mindplay-dk** [comment]
@michaelcullum ping?

**Comment by mindplay-dk** [comment]
Well, to anyone else looking - I've put up a temporary replacement fork that replaces `psr/simple-cache^0.1` so you can install this for now, if needed.

(Note that I will abandon this package as soon as there's an official release.)

**Comment by michaelcullum** [comment]
We can do I suppose if @php-fig/psr-16 have no objections?

**Comment by mindplay-dk** [comment]
@michaelcullum unrelated, but any particular reason why @php-fig/psr-16 is a private team listing?

**Comment by Seldaek** [comment]
I'll try to look at this next few days.. sorry for the delay on PSR-16, been really busy lately :/

**Comment by dragoonis** [comment]
Hello guys,

In future if you need something on this PSR just email me directly or tweet
me and i woll get right on it.

I guess michael is setting up the packagist so will leave it at that.

Cheers

**Comment by michaelcullum** [comment]
The PSR-16 team isn't secret?

As @php-fig/psr-16 are cool with it I'll do the tag now.

**Comment by michaelcullum** [comment]
Done. :)

**Comment by mindplay-dk** [comment]
> The PSR-16 team isn't secret?

`https://github.com/orgs/php-fig/teams/psr-16` throws a 404 for me.

**Comment by michaelcullum** [comment]
@mindplay-dk Github only has visible and secret teams. Visible teams are only visible to org members though. See https://help.github.com/articles/creating-a-team/
