### ISSUE TITLE
RFC: Remove `*Multiple()` methods

### ISSUE THREAD

**Issue by nicolas-grekas** [php-fig/simplecache#3]
While working on using PSR-6 in Symfony, I found several places in several components where we needed cache, but none of them where actually getting several keys at once.
Hence, I'm wondering if the *simple* cache PSR should have these `*Multiple` at all.
The justification for this new PSR is that it covers the simplest yet more common use cases for cache stores. Looking at Symfony, the `*Multiple` methods do not qualify for this definition.
What about considering that for people needing them, they should use straight PSR-6 instead?

**Comment by Seldaek** [comment]
The Simple of simple-cache means *simple to use* in my mind, not *the most simplistic features*. So as such I would say rather keep them in as they are very easy to implement for PSR-6 implementors and even I'd suspect for PSR-16 implementors, and they might not provide value to a lot of people but the cost of having them there is near zero.

**Comment by nicolas-grekas** [comment]
> "Perfection is Achieved Not When There Is Nothing More to Add, But When There Is Nothing Left to Take Away"

;-)

**Comment by Seldaek** [comment]
That doesn't mean it isn't perfect right now :p
